%CALCULATE STRESS FROM DISPLACEMENT DATA
function [elStress] = feaStress(elementDef, numEl, nodeDisp, elLength, youngM, area, elAngle)
stress = zeros(numEl, 1);
sigma = [];
for i=1:numEl
    startNode = elementDef(i, 1);
    endNode = elementDef(i, 2);
    sigma = [sigma; ...
    youngM(i) / elLength(i) * ...
    [cosd(elAngle(i)) sind(elAngle(i)) -cosd(elAngle(i)) -sind(elAngle(i))] * ...
    [nodeDisp(2*startNode-1); ...
    nodeDisp(2*startNode); ...
    nodeDisp(2*endNode-1, 1); ...
    nodeDisp(2*endNode)]];
end
elStress = -sigma;